server:
  port: 8080

spring:
  application:
    name: @project.build.finalName@
    version: @project.version@
    description: @project.description@
#  profiles:
#    active: @project.activeProfile@