eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    prefer-ip-address: true

services:
  userService:
    baseUrl: ${USER_SERVICE_BASE_URL:http://user-service/internal/api}